on:
  push:
    branches:
    - master

name: Publish
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install static-check
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        staticcheck ./...
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
